// This file is generated by rust-protobuf 3.0.3. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `vesting.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_0_3;

///  Coin defines a token with a denomination and an amount.
///
///  NOTE: The amount field is an Int which implements the custom method
///  signatures required by gogoproto.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:cosmos.vesting.v1beta1.Coin)
pub struct Coin {
    // message fields
    // @@protoc_insertion_point(field:cosmos.vesting.v1beta1.Coin.denom)
    pub denom: ::std::string::String,
    // @@protoc_insertion_point(field:cosmos.vesting.v1beta1.Coin.amount)
    pub amount: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:cosmos.vesting.v1beta1.Coin.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Coin {
    fn default() -> &'a Coin {
        <Coin as ::protobuf::Message>::default_instance()
    }
}

impl Coin {
    pub fn new() -> Coin {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "denom",
            |m: &Coin| { &m.denom },
            |m: &mut Coin| { &mut m.denom },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "amount",
            |m: &Coin| { &m.amount },
            |m: &mut Coin| { &mut m.amount },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Coin>(
            "Coin",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Coin {
    const NAME: &'static str = "Coin";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.denom = is.read_string()?;
                },
                18 => {
                    self.amount = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.denom.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.denom);
        }
        if !self.amount.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.amount);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.denom.is_empty() {
            os.write_string(1, &self.denom)?;
        }
        if !self.amount.is_empty() {
            os.write_string(2, &self.amount)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Coin {
        Coin::new()
    }

    fn clear(&mut self) {
        self.denom.clear();
        self.amount.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Coin {
        static instance: Coin = Coin {
            denom: ::std::string::String::new(),
            amount: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Coin {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Coin").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Coin {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Coin {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Period defines a length of time and amount of coins that will vest.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:cosmos.vesting.v1beta1.Period)
pub struct Period {
    // message fields
    // @@protoc_insertion_point(field:cosmos.vesting.v1beta1.Period.length)
    pub length: i64,
    // @@protoc_insertion_point(field:cosmos.vesting.v1beta1.Period.amount)
    pub amount: ::std::vec::Vec<Coin>,
    // special fields
    // @@protoc_insertion_point(special_field:cosmos.vesting.v1beta1.Period.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Period {
    fn default() -> &'a Period {
        <Period as ::protobuf::Message>::default_instance()
    }
}

impl Period {
    pub fn new() -> Period {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "length",
            |m: &Period| { &m.length },
            |m: &mut Period| { &mut m.length },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "amount",
            |m: &Period| { &m.amount },
            |m: &mut Period| { &mut m.amount },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Period>(
            "Period",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Period {
    const NAME: &'static str = "Period";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.length = is.read_int64()?;
                },
                18 => {
                    self.amount.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.length != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.length);
        }
        for value in &self.amount {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.length != 0 {
            os.write_int64(1, self.length)?;
        }
        for v in &self.amount {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Period {
        Period::new()
    }

    fn clear(&mut self) {
        self.length = 0;
        self.amount.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Period {
        static instance: Period = Period {
            length: 0,
            amount: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Period {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Period").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Period {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Period {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  MsgCreateVestingAccount defines a message that enables creating a vesting
///  account.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccount)
pub struct MsgCreatePeriodicVestingAccount {
    // message fields
    // @@protoc_insertion_point(field:cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccount.from_address)
    pub from_address: ::std::string::String,
    // @@protoc_insertion_point(field:cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccount.to_address)
    pub to_address: ::std::string::String,
    // @@protoc_insertion_point(field:cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccount.start_time)
    pub start_time: i64,
    // @@protoc_insertion_point(field:cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccount.vesting_periods)
    pub vesting_periods: ::std::vec::Vec<Period>,
    // special fields
    // @@protoc_insertion_point(special_field:cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccount.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MsgCreatePeriodicVestingAccount {
    fn default() -> &'a MsgCreatePeriodicVestingAccount {
        <MsgCreatePeriodicVestingAccount as ::protobuf::Message>::default_instance()
    }
}

impl MsgCreatePeriodicVestingAccount {
    pub fn new() -> MsgCreatePeriodicVestingAccount {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "from_address",
            |m: &MsgCreatePeriodicVestingAccount| { &m.from_address },
            |m: &mut MsgCreatePeriodicVestingAccount| { &mut m.from_address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "to_address",
            |m: &MsgCreatePeriodicVestingAccount| { &m.to_address },
            |m: &mut MsgCreatePeriodicVestingAccount| { &mut m.to_address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "start_time",
            |m: &MsgCreatePeriodicVestingAccount| { &m.start_time },
            |m: &mut MsgCreatePeriodicVestingAccount| { &mut m.start_time },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "vesting_periods",
            |m: &MsgCreatePeriodicVestingAccount| { &m.vesting_periods },
            |m: &mut MsgCreatePeriodicVestingAccount| { &mut m.vesting_periods },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MsgCreatePeriodicVestingAccount>(
            "MsgCreatePeriodicVestingAccount",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MsgCreatePeriodicVestingAccount {
    const NAME: &'static str = "MsgCreatePeriodicVestingAccount";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.from_address = is.read_string()?;
                },
                18 => {
                    self.to_address = is.read_string()?;
                },
                24 => {
                    self.start_time = is.read_int64()?;
                },
                34 => {
                    self.vesting_periods.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.from_address.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.from_address);
        }
        if !self.to_address.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.to_address);
        }
        if self.start_time != 0 {
            my_size += ::protobuf::rt::int64_size(3, self.start_time);
        }
        for value in &self.vesting_periods {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.from_address.is_empty() {
            os.write_string(1, &self.from_address)?;
        }
        if !self.to_address.is_empty() {
            os.write_string(2, &self.to_address)?;
        }
        if self.start_time != 0 {
            os.write_int64(3, self.start_time)?;
        }
        for v in &self.vesting_periods {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MsgCreatePeriodicVestingAccount {
        MsgCreatePeriodicVestingAccount::new()
    }

    fn clear(&mut self) {
        self.from_address.clear();
        self.to_address.clear();
        self.start_time = 0;
        self.vesting_periods.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MsgCreatePeriodicVestingAccount {
        static instance: MsgCreatePeriodicVestingAccount = MsgCreatePeriodicVestingAccount {
            from_address: ::std::string::String::new(),
            to_address: ::std::string::String::new(),
            start_time: 0,
            vesting_periods: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MsgCreatePeriodicVestingAccount {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MsgCreatePeriodicVestingAccount").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MsgCreatePeriodicVestingAccount {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MsgCreatePeriodicVestingAccount {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\rvesting.proto\x12\x16cosmos.vesting.v1beta1\"4\n\x04Coin\x12\x14\n\
    \x05denom\x18\x01\x20\x01(\tR\x05denom\x12\x16\n\x06amount\x18\x02\x20\
    \x01(\tR\x06amount\"V\n\x06Period\x12\x16\n\x06length\x18\x01\x20\x01(\
    \x03R\x06length\x124\n\x06amount\x18\x02\x20\x03(\x0b2\x1c.cosmos.vestin\
    g.v1beta1.CoinR\x06amount\"\xcb\x01\n\x1fMsgCreatePeriodicVestingAccount\
    \x12!\n\x0cfrom_address\x18\x01\x20\x01(\tR\x0bfromAddress\x12\x1d\n\nto\
    _address\x18\x02\x20\x01(\tR\ttoAddress\x12\x1d\n\nstart_time\x18\x03\
    \x20\x01(\x03R\tstartTime\x12G\n\x0fvesting_periods\x18\x04\x20\x03(\x0b\
    2\x1e.cosmos.vesting.v1beta1.PeriodR\x0evestingPeriodsJ\xfc\x06\n\x06\
    \x12\x04\0\0\x1b\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\
    \x03\x02\0\x1f\n\xaf\x01\n\x02\x04\0\x12\x04\x08\0\x0b\x03\x1a\xa2\x01\
    \x20Coin\x20defines\x20a\x20token\x20with\x20a\x20denomination\x20and\
    \x20an\x20amount.\n\n\x20NOTE:\x20The\x20amount\x20field\x20is\x20an\x20\
    Int\x20which\x20implements\x20the\x20custom\x20method\n\x20signatures\
    \x20required\x20by\x20gogoproto.\n\n\n\n\x03\x04\0\x01\x12\x03\x08\x08\
    \x0c\n\x0b\n\x04\x04\0\x02\0\x12\x03\t\x04\x16\n\x0c\n\x05\x04\0\x02\0\
    \x05\x12\x03\t\x04\n\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\t\x0b\x10\n\x0c\
    \n\x05\x04\0\x02\0\x03\x12\x03\t\x14\x15\n\x0b\n\x04\x04\0\x02\x01\x12\
    \x03\n\x04\x16\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\n\x04\n\n\x0c\n\x05\
    \x04\0\x02\x01\x01\x12\x03\n\x0b\x11\n\x0c\n\x05\x04\0\x02\x01\x03\x12\
    \x03\n\x14\x15\nQ\n\x02\x04\x01\x12\x04\x0f\0\x12\x03\x1aE\x20Period\x20\
    defines\x20a\x20length\x20of\x20time\x20and\x20amount\x20of\x20coins\x20\
    that\x20will\x20vest.\n\n\n\n\x03\x04\x01\x01\x12\x03\x0f\x08\x0e\n\x0b\
    \n\x04\x04\x01\x02\0\x12\x03\x10\x041\n\x0c\n\x05\x04\x01\x02\0\x05\x12\
    \x03\x10\x04\t\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x10\r\x13\n\x0c\n\
    \x05\x04\x01\x02\0\x03\x12\x03\x10/0\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\
    \x11\x04\x1d\n\x0c\n\x05\x04\x01\x02\x01\x04\x12\x03\x11\x04\x0c\n\x0c\n\
    \x05\x04\x01\x02\x01\x06\x12\x03\x11\r\x11\n\x0c\n\x05\x04\x01\x02\x01\
    \x01\x12\x03\x11\x12\x18\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\x11\x1b\
    \x1c\na\n\x02\x04\x02\x12\x04\x16\0\x1b\x01\x1aU\x20MsgCreateVestingAcco\
    unt\x20defines\x20a\x20message\x20that\x20enables\x20creating\x20a\x20ve\
    sting\n\x20account.\n\n\n\n\x03\x04\x02\x01\x12\x03\x16\x08'\n\x0b\n\x04\
    \x04\x02\x02\0\x12\x03\x17\x041\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03\
    \x17\x04\n\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x17\r\x19\n\x0c\n\x05\
    \x04\x02\x02\0\x03\x12\x03\x17/0\n\x0b\n\x04\x04\x02\x02\x01\x12\x03\x18\
    \x041\n\x0c\n\x05\x04\x02\x02\x01\x05\x12\x03\x18\x04\n\n\x0c\n\x05\x04\
    \x02\x02\x01\x01\x12\x03\x18\r\x17\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\
    \x03\x18/0\n\x0b\n\x04\x04\x02\x02\x02\x12\x03\x19\x041\n\x0c\n\x05\x04\
    \x02\x02\x02\x05\x12\x03\x19\x04\t\n\x0c\n\x05\x04\x02\x02\x02\x01\x12\
    \x03\x19\r\x17\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03\x19/0\n\x0b\n\x04\
    \x04\x02\x02\x03\x12\x03\x1a\x04(\n\x0c\n\x05\x04\x02\x02\x03\x04\x12\
    \x03\x1a\x04\x0c\n\x0c\n\x05\x04\x02\x02\x03\x06\x12\x03\x1a\r\x13\n\x0c\
    \n\x05\x04\x02\x02\x03\x01\x12\x03\x1a\x14#\n\x0c\n\x05\x04\x02\x02\x03\
    \x03\x12\x03\x1a&'b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(Coin::generated_message_descriptor_data());
            messages.push(Period::generated_message_descriptor_data());
            messages.push(MsgCreatePeriodicVestingAccount::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
